### ISSUE TITLE
Can't build lsyncd on debian

### ISSUE THREAD

**Issue by racinmat** [lsyncd/lsyncd#683]
Running following installation steps:
```bash
mkdir -p lsyncd
wget -c https://github.com/lsyncd/lsyncd/archive/refs/tags/v2.3.0.tar.gz -O - | tar -xz -C ./lsyncd
cd lsyncd/lsyncd-2.3.0/
sudo apt-get update && sudo apt-get install -y cmake build-essential liblua5.4 rsync
cmake .
make
```
leads to error
```
Scanning dependencies of target prepare_tests
failed to create symbolic link 'tests' because existing path cannot be removed: Is a directory
make[2]: *** [CMakeFiles/prepare_tests.dir/build.make:76: CMakeFiles/prepare_tests] Error 1
make[1]: *** [CMakeFiles/Makefile2:127: CMakeFiles/prepare_tests.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
debian@ostrakon:~/infrastructure/k3s/lsyncd/lsyncd-2.3.0$ ls -lh

```

**Comment by adfruin** [comment]
Same on Ubuntu 20.04

failed to create symbolic link 'tests' because existing path cannot be removed: Is a directory
make[2]: *** [CMakeFiles/prepare_tests.dir/build.make:57: CMakeFiles/prepare_tests] Error 1
make[1]: *** [CMakeFiles/Makefile2:108: CMakeFiles/prepare_tests.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by Hvonnus** [comment]
Hi, not sure if it helps but I have just tried this exact sequence on ubuntu 20.04 as explained in INSTALL file and it worked 

```
git clone https://github.com/lsyncd/lsyncd.git
sudo apt install lua5.3
sudo apt install liblua5.3-dev
sudo snap install cmake
mkdir build
cd build/
cmake ..
make
sudo make install
```

**Comment by poelzi** [comment]
Building inside the src directory is highly discouraged with all cmake based projects.
I changed the build script in d779eb4 to not fail anymore. Anyways, not recommended :)

**Comment by racinmat** [comment]
And what is the correct way to build it and could it be included in the docs?

**Comment by axkibe** [comment]
To be fair, back the day I wrote the manual using in place builds. Might be sensible to update the manual using a build directory.

https://lsyncd.github.io/lsyncd/manual/building/

This tests thing with cmake has otherwise always been an issue / a little mess from my side, due the unit tests being part of the repository, but not part of the release, yet part of the build system to perform the unit tests if desired.
